services:
    db:
        image: postgres:15
        container_name: kingsmaker_db
        restart: always
        ports:
            - "7432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: kingsmaker
        volumes:
            - postgres-data:/var/lib/postgresql/data

    redis:
        image: redis:7-alpine
        container_name: kingsmaker_redis
        restart: always
        ports:
            - "7379:6379"
        volumes:
            - redis-data:/data
        command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

    auth:
        build:
            context: .
            dockerfile: services/auth/Dockerfile
        container_name: auth_service
        ports:
            - "7001:3000"
        depends_on:
            - db
        environment:
            DATABASE_URL: postgresql://postgres:postgres@db:5432/kingsmaker

    chat:
        build:
            context: .
            dockerfile: services/chat/Dockerfile
        container_name: chat_service
        ports:
            - "7002:3000"
        depends_on:
            - db
        environment:
            DATABASE_HOST: db
            DATABASE_USER: postgres
            DATABASE_PASSWORD: postgres
            DATABASE_NAME: kingsmaker
            DATABASE_PORT: 5432

    game:
        build:
            context: .
            dockerfile: services/game/Dockerfile
        container_name: game_service
        ports:
            - "7003:3000"
        depends_on:
            - db
        environment:
            DATABASE_HOST: db
            DATABASE_USER: postgres
            DATABASE_PASSWORD: postgres
            DATABASE_NAME: kingsmaker
            DATABASE_PORT: 5432

    lobby:
        build:
            context: .
            dockerfile: services/lobby/Dockerfile
        container_name: lobby_service
        ports:
            - "7004:3000"
        depends_on:
            - db
            - redis
        environment:
            DATABASE_HOST: db
            DATABASE_USER: postgres
            DATABASE_PASSWORD: postgres
            DATABASE_NAME: kingsmaker
            DATABASE_PORT: 5432
            REDIS_HOST: redis
            REDIS_PORT: 6379

    waitingroom:
        build:
            context: .
            dockerfile: services/waitingRoom/Dockerfile
        container_name: waitingroom_service
        ports:
            - "7005:3000"
        depends_on:
            - db
            - redis
        environment:
            DATABASE_HOST: db
            DATABASE_USER: postgres
            DATABASE_PASSWORD: postgres
            DATABASE_NAME: kingsmaker
            DATABASE_PORT: 5432
            REDIS_HOST: redis
            REDIS_PORT: 6379

    store:
        build:
            context: .
            dockerfile: services/store/Dockerfile
        container_name: store_service
        ports:
            - "7006:3000"
        depends_on:
            - db
        environment:
            DATABASE_HOST: db
            DATABASE_USER: postgres
            DATABASE_PASSWORD: postgres
            DATABASE_NAME: kingsmaker
            DATABASE_PORT: 5432

volumes:
    postgres-data:
    redis-data:
