version: '3.8'

services:
  db:
    image: postgres:15
    container_name: kingsmaker_db
    restart: always
    ports:
      - "7000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kingsmaker
    volumes:
      - postgres-data:/var/lib/postgresql/data

  auth:
    build: ./services/auth
    container_name: auth_service
    ports:
      - "7001:3000"
    depends_on:
      - db

  chat:
    build: ./services/chat
    container_name: chat_service
    ports:
      - "7002:3000"
    depends_on:
      - db

  game:
    build: ./services/game
    container_name: game_service
    ports:
      - "7003:3000"
    depends_on:
      - db

  lobby:
    build: ./services/lobby
    container_name: lobby_service
    ports:
      - "7004:3000"
    depends_on:
      - db

  waitingroom:
    build: ./services/waitingRoom
    container_name: waitingroom_service
    ports:
      - "7005:3000"
    depends_on:
      - db

  store:
    build: ./services/store
    container_name: store_service
    ports:
      - "7006:3000"
    depends_on:
      - db

volumes:
  postgres-data: